# Generated by Django 3.1.2 on 2020-10-28 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=200)),
                ('input_type', models.IntegerField(default=0)),
                ('typing_speed', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('erased_letter', models.CharField(max_length=10)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_speed', models.FloatField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstone.sentence')),
            ],
        ),
    ]
